// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tDDMWtWzaxS29CaTYSwv0ejzBsPFAh4',
    appId: '1:414007904996:web:b7fcdc2406b3a39e5efaf1',
    messagingSenderId: '414007904996',
    projectId: 'remainder-5bf31',
    authDomain: 'remainder-5bf31.firebaseapp.com',
    storageBucket: 'remainder-5bf31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9UZ3b1Mp_ePWmjPFMHa6pHbCpYIWXw8',
    appId: '1:414007904996:android:fa1320c3dc0608275efaf1',
    messagingSenderId: '414007904996',
    projectId: 'remainder-5bf31',
    storageBucket: 'remainder-5bf31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQsp8nYx0M-X5b4bfzPQDNJFd37bW6oQ',
    appId: '1:414007904996:ios:6d4fad191e72af715efaf1',
    messagingSenderId: '414007904996',
    projectId: 'remainder-5bf31',
    storageBucket: 'remainder-5bf31.firebasestorage.app',
    iosBundleId: 'com.example.remainder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUQsp8nYx0M-X5b4bfzPQDNJFd37bW6oQ',
    appId: '1:414007904996:ios:6d4fad191e72af715efaf1',
    messagingSenderId: '414007904996',
    projectId: 'remainder-5bf31',
    storageBucket: 'remainder-5bf31.firebasestorage.app',
    iosBundleId: 'com.example.remainder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7tDDMWtWzaxS29CaTYSwv0ejzBsPFAh4',
    appId: '1:414007904996:web:34949115c01f1f245efaf1',
    messagingSenderId: '414007904996',
    projectId: 'remainder-5bf31',
    authDomain: 'remainder-5bf31.firebaseapp.com',
    storageBucket: 'remainder-5bf31.firebasestorage.app',
  );

}